# Form implementation generated from reading ui file 'selecet-center-window_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from gui.master_window import MasterWindow
from PyQt6 import uic

class SelectCenterWindow(QMainWindow):
    def __init__(self, master_window: MasterWindow):
        super.__init__()
        self.ui = uic.load_ui("../ui-files/selecet-center-window_design.ui", self)
        self.master_window = master_window