# Form implementation generated from reading ui file 'selecet-center-window_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from gui.master_window import MasterWindow
from PyQt6 import uic
from gui.file_selection_window import FileSelectionWindow

class SelectCenterWindow(QMainWindow):
    def __init__(self, master_window: MasterWindow):
        super().__init__()
        self.ui = uic.loadUi("./ui-files/select_center_window_design.ui", self)
        self.master_window = master_window
        self.ui.enter_button.clicked.connect(self.__onEnter)

    def __onEnter(self):
        selected_center = self.ui.center_list_box.currentText()
        self.master_window.switch_to(FileSelectionWindow(self.master_window, selected_center))
